## Google: Gauss Elimination Wiki

In [ ]:
Tem divisão por zero
Sempre a primeira linha sendo utilizada pro calculo?

In [60]:
#https://en.wikipedia.org/wiki/Gaussian_elimination (Fazer o exemplo e dizer por que não funciona)
M = np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
b = np.array([[8],[-11],[-3]])

Matriz = [[1,3,1],[1,1,-1],[3,11,5]] 
Vetor = [9,1,35]

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    
    for k in range(0,n-1):
        for i in range(k+1,n):

            print("a[i][k]",a[i][k])
            print("a[K][k]",a[k][k])
            
            m=a[i][k]/a[k][k]
            
            print("ESSE E O M", m)
            
            a[i][k] = 0
            print("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa a[i][k] = 0")
            for j in range(k+1,n):
                print("  ")
                print(a)
                print("  ")
                print("a[i][j]",a[i][j])
                print("             ")
                print("a[k][j]",a[k][j])
                print("ESSE E O M", m)
                a[i][j] = a[i][j] - m*a[k][j]
                b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]
a[i][k] -3
a[K][k] 2
ESSE E O M -1.5
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa a[i][k] = 0
  
[[ 2  1 -1]
 [ 0 -1  2]
 [-2  1  2]]
  
a[i][j] -1
             
a[k][j] 1
ESSE E O M -1.5
  
[[ 2  1 -1]
 [ 0  0  2]
 [-2  1  2]]
  
a[i][j] 2
             
a[k][j] -1
ESSE E O M -1.5
a[i][k] -2
a[K][k] 2
ESSE E O M -1.0
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa a[i][k] = 0
  
[[ 2  1 -1]
 [ 0  0  0]
 [ 0  1  2]]
  
a[i][j] 1
             
a[k][j] 1
ESSE E O M -1.0
  
[[ 2  1 -1]
 [ 0  0  0]
 [ 0  2  2]]
  
a[i][j] 2
             
a[k][j] -1
ESSE E O M -1.0
a[i][k] 2
a[K][k] 0
ESSE E O M inf
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa a[i][k] = 0
  
[[ 2  1 -1]
 [ 0  0  0]
 [ 0  0  1]]
  
a[i][j] 1
             
a[k][j] 0
ESSE E O M inf


C:\Users\aczal\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: divide by zero encountered in long_scalars
C:\Users\aczal\Anaconda3\lib\site-packages\ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in double_scalars


ValueError: cannot convert float NaN to integer

## Adicionando condições ao código

In [ ]:
'''
Duas condições
-Se elemento zero abaixo do pivô: continue. 
-Se um dos pivôs for zero mostrar mensagem de erro
(Sistema não tem solução se o determinante for igual a zero)
'''

In [2]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[k][k] == 0:
                print("Pivo igual a zero, meu")
            m=a[i][k]/a[k][k]
            a[i][k] = 0
            for j in range(k+1,n):
                a[i][j] = a[i][j] - m*a[k][j]
                b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 1 -1  2]
 [ 2  1 -1]
 [-2 -5  3]]
[[ 2]
 [-7]
 [-5]]


In [ ]:
P/ casa(3)

In [ ]:
#Se determinante = 0: mensagem de erro
# else: aplicar gaussElmination
#np.linalg.det(a) pra calcular o determinante

In [17]:
def PivParcial():
    

M = np.array([[1,2,3,4], [0,5,6,7], [0,0,8,9],[0,0,0,10]])
b = np.array([5,4,4,2])

print("Matriz exemplo")
print(M)

def ResolSisTriang(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k+1,n):
            s = s + a[k][j]*x[j]
        x[k] = (b[k]-s)/a[k][k]
    return x

ResolSisTriang(M,b)
#troc linha por coluna = pivoteamento completo
#troc linha por linha = parcial

Matriz exemplo
[[ 1  2  3  4]
 [ 0  5  6  7]
 [ 0  0  8  9]
 [ 0  0  0 10]]


[2.9950000000000001,
 0.18999999999999995,
 0.27500000000000002,
 0.20000000000000001]

## Inserir o trecho de código abaixo na função de resolução de sistema triangular

In [27]:
#colocar esse código dentro do de resolução de sistema triangular
#Pivoteamento parcial

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


A = Amat
print(A)

k = 1
i = 2
n = np.shape(A)[0] - 1#último index
print('n ', n, '\n')

#slicing
#Pegando a parte que ta abaixo do pivô
print( np.array( A[ i : n + 1, k ] ) )

#Localizando o  maior valor na coluna do pivô, depois do pivô
col = A[ i : n + 1, k ]

colAbs = np.abs( col )
print( 'colAbs \n', colAbs )

#Retorna o index do valor máximo
indexMax = np.argmax( colAbs )
print( indexMax )


#Trocando a coluna
iChange = indexMax + i
print( iChange )

aux = np.copy( A[ k, : ] )
print( aux )

#trocando a linha
A[ k, : ] = np.copy( A[ iChange, : ] )
A[ iChange, : ] = np.copy( aux )

print(A)

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 

[[-3]
 [ 2]]
colAbs 
 [[3]
 [2]]
0
2
[[0 1 0 3]]
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]


In [32]:
import numpy as np

def pivoteamentoParcial(A, k, i):

  n = np.shape(A)[0] - 1 #último index
  print('n Ultimo ', n, '\n')

  #slicing
  print( np.array( A[ i : n + 1, k ] ) )

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )
  print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  print(A)

  return A



def eliminacaoDegauss( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #
        print('k ', k)
        for i in np.arange( k + 1, n + 1 ): #Eliminação em cada linha
            print('i', i )
            A = pivoteamentoParcial(A,k,i) 
            m = A[ i, k ] / A[ k, k ] #Se for considerada divisão de inteiros dará zero
            print('m ', m) 
            A[ i, k ] = 0
            for j in np.arange( k + 1, n + 1 ):
                print('j', j )
        
    return A



b = np.array( [ 5., 6., 7., 15. ] )

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])

A = Amat
print(A)

n = np.shape(A)[0] - 1#último index
print('n ', n)

eliminacaoDegauss( np.copy( A ), np.copy( b ), n )

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3
k  1
i 2
n Ultimo  3 

[-3  2]
colAbs 
 [3 2]
0
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]
m  -0.3333333333333333
j 2
j 3
i 3
n Ultimo  3 

[2]
colAbs 
 [2]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0  0  3]
 [ 0 -3 -5  7]]
m  -1.5
j 2
j 3
k  2
i 3
n Ultimo  3 

[-5]
colAbs 
 [5]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]
m  -0.0
j 3


array([[ 3,  2,  4, -1],
       [ 0,  2,  4,  0],
       [ 0,  0, -5,  7],
       [ 0,  0,  0,  3]])

## Resolução de exemplo em sala

In [19]:
M = np.array([[0.0002, 2],[2,2]])
b = np.array([5, 6])
x = np.linalg.solve(M,b)
print(x)

[ 0.50005001  2.49994999]


In [ ]:
#Atividade pra casa
Passar matriz A, matriz B e número de dígitos da máquina. 