Índice

- [Google: Gauss Elimination Wiki](#Google:-Gauss-Elimination-Wiki)
- [Adicionando melhorias ao código](#Adicionando-melhorias-ao-código)
- [Inserir o codigo de piv parcial na função de resolução de sistema triangular](#Inserir-o-codigo-de-piv-parcial-na-função-de-resolução-de-sistema-triangular) 
- [Simulação de máquina de resolução de sistemas lineares com precisão t](#Simulação-de-máquina-de-resolução-de-sistemas-lineares-com-precisão-t)
- [Resolução dos sistemas triangulares gerados](#Resolução-dos-sistemas-triangulares-gerados)
- [Resposta exata](#Resposta-exata)

## Google: Gauss Elimination Wiki

In [ ]:
'''
- Se for considerado uma Matriz de inteiros, vai dar erro porque em um momento o pivô vai ser zero e vai encerrar a execução.
- Com números floats ele faz o processo com valores aproximados.
'''

In [935]:
#https://en.wikipedia.org/wiki/Gaussian_elimination (Fazer o exemplo e dizer por que não funciona)
M = np.array([[2.,1.,-1.],[-3.,-1.,2.],[-2.,1.,2.]])
b = np.array([[8.],[-11.],[-3.]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
        return print("o DETERMINANTE E ZERO")
    else:
        for k in range(0,n-1):
            for i in range(k+1,n):
                if a[k][k] == 0:
                    print("ERRO: PIVÔ IGUAL A ZERO")
                m=a[i][k]/a[k][k]
                if a[i][k] == 0:
                    continue
                a[i][k] = 0
                for j in range(k+1,n):
                    a[i][j] = a[i][j] - m*a[k][j]
                    b[i] = b[i] - m*b[k]
    print (a)

eliminacao(M,b)
print(b)

matriz exemplo
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]
[[  8.]
 [ 13.]
 [-39.]]


## Adicionando melhorias ao código

In [ ]:
'''
Duas condições:
-Se elemento zero abaixo do pivô: continue. 
-Se um dos pivôs for zero mostrar mensagem de erro
(Sistema não tem solução se o determinante for igual a zero)
'''

In [2]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[k][k] == 0:
                print("ERRO: PIVÔ IGUAL A ZERO")
            m=a[i][k]/a[k][k]
            if a[i][k] == 0:
                continue
            a[i][k] = 0
            for j in range(k+1,n):
                a[i][j] = a[i][j] - m*a[k][j]
                b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 1 -1  2]
 [ 2  1 -1]
 [-2 -5  3]]
[[ 2]
 [-7]
 [-5]]


In [ ]:
'''
Se determinante = 0: mensagem de erro
else: aplicar gaussElmination
np.linalg.det(a) pra calcular o determinante
'''

In [ ]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
        return print("o DETERMINANTE E ZERO")
    else:
        for k in range(0,n-1):
            for i in range(k+1,n):
                if a[k][k] == 0:
                    print("ERRO: PIVÔ IGUAL A ZERO")
                m=a[i][k]/a[k][k]
                if a[i][k] == 0:
                    continue
                a[i][k] = 0
                for j in range(k+1,n):
                    a[i][j] = a[i][j] - m*a[k][j]
                    b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

## Inserir o codigo de piv parcial na função de resolução de sistema triangular

In [27]:
#colocar esse código dentro do de resolução de sistema triangular
#Pivoteamento parcial

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


A = Amat
print(A)

k = 1
i = 2
n = np.shape(A)[0] - 1#último index
print('n ', n, '\n')

#slicing
#Pegando a parte que ta abaixo do pivô
print( np.array( A[ i : n + 1, k ] ) )

#Localizando o  maior valor na coluna do pivô, depois do pivô
col = A[ i : n + 1, k ]

colAbs = np.abs( col )
print( 'colAbs \n', colAbs )

#Retorna o index do valor máximo
indexMax = np.argmax( colAbs )
print( indexMax )


#Trocando a coluna
iChange = indexMax + i
print( iChange )

aux = np.copy( A[ k, : ] )
print( aux )

#trocando a linha
A[ k, : ] = np.copy( A[ iChange, : ] )
A[ iChange, : ] = np.copy( aux )

print(A)

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 

[[-3]
 [ 2]]
colAbs 
 [[3]
 [2]]
0
2
[[0 1 0 3]]
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]


In [756]:
import numpy as np

def pivoteamentoParcial(A, k, i):

  n = np.shape(A)[0] - 1 #último index
  print('n Ultimo ', n, '\n')

  #slicing
  print( np.array( A[ i : n + 1, k ] ) )

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )
  print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  print(A)

  return A



def eliminacaoDegauss( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #
        print('k ', k)
        for i in np.arange( k + 1, n + 1 ): #Eliminação em cada linha
            print('i', i )
            A = pivoteamentoParcial(A,k,i) 
            m = A[ i, k ] / A[ k, k ] #Se for considerada divisão de inteiros dará zero
            print('m ', m) 
            A[ i, k ] = 0
            for j in np.arange( k + 1, n + 1 ):
                print('j', j )
        
    return A




b = np.array( [ 5, 6., 7., 15. ] )

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])

A = Amat
print(A)

n = np.shape(A)[0] - 1#último index
print('n ', n)

eliminacaoDegauss( np.copy( A ), np.copy( b ), n )

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3
k  1
i 2
n Ultimo  3 

[-3  2]
colAbs 
 [3 2]
0
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]
m  -0.3333333333333333
j 2
j 3
i 3
n Ultimo  3 

[2]
colAbs 
 [2]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0  0  3]
 [ 0 -3 -5  7]]
m  -1.5
j 2
j 3
k  2
i 3
n Ultimo  3 

[-5]
colAbs 
 [5]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]
m  -0.0
j 3


array([[ 3,  2,  4, -1],
       [ 0,  2,  4,  0],
       [ 0,  0, -5,  7],
       [ 0,  0,  0,  3]])

## Resolução de exemplo em sala

In [19]:
M = np.array([[0.0002, 2],[2,2]])
b = np.array([5, 6])
x = np.linalg.solve(M,b)
print(x)

[ 0.50005001  2.49994999]


## Simulação de máquina de resolução de sistemas lineares com precisão t

In [ ]:
#Atividade pra casa
Passar matriz A, matriz B e número de dígitos da máquina. 

Fazer o def que simule a última parte da apresentação Resolução de Sistemas Lineares - Método da Eliminação de Gauss,
na qual um máquina com precisão t é usada obter a resposta de um sistema linear com e sem pivoteamento parcial. 
O def tem como parâmetros a matriz A, b e t dígitos, pelo menos. 
Deve retornar a resposta do sistema e também se a resposta está correta. 
Fazer um código    genérico, que funcione para outras matrizes A e diferentes precisões t. 
Usar o exemplo que foi apresentado em sala de aula para testar o def.

Nota: para somar ou subtrair dois números, o expoente menor deve ser igualado ao expoente maior.

In [951]:
def Truncamento(num, exp, lim):
  sinal = ''
  if (int(num.split('.')[0])>0 or (int(num.split('.')[0])<0) ) :
     
    parteInt=str(len(num.split('.')[0]))
    
    
    if(num[0] == '-'):
      sinal = num[0]
      print(sinal)
      num = num.replace(num[0],"")
      fracao = num.split('.')[0]

    elif(num[0]==0 and num[0] != '-'):
        fracao=num.split('.')[0] + num.split('.')[1] 
    else:
        fracao=num.split('.')[0] 
        

    if(len(fracao)>lim): fracao=fracao[:lim] 
    
    if(int(parteInt)>exp):
      fracao=str(sinal) + '0.' + fracao + '*10**' + str(exp)
    else: 
      fracao='0.' + fracao + '*10**' + parteInt

  else:
    if(num[0] == '-'):
      sinal = num[0]

    fracao=num.split('.')[1] 

    i=0
    while (True):
      if (fracao[i]=='0'): i+=1
      else: break
    fracao= fracao.replace('0', '', i)

    if (len(fracao)>lim): fracao=fracao[:lim]

    if (i>=exp): 
      fracao= str(sinal) + '0.' + fracao + '*10**-' + str(exp)
    elif (i==0): 
      
      fracao= str(sinal) + '0.' + fracao + '*10**0'
    else: 
      str(i)
      new_exp = int('-'+str(i)) 
      fracao= str(sinal) + '0.' + fracao + '*10**-' + str(i)

  #print('Truncamento:', fracao)
  return fracao



M = np.array([['0.0002      ', '2'] , ['2' , '2']])
b = (['5','6'])
t = 3
n = len (M)
#n = np.shape(M)[0] - 1#último index



def maquina(M,b,t):
    #print("Matriz exemplo")
    #print(M)
    
    #fracoes = []
    #expoentes = []
    
    
    n = len(M)
    for k in range(0,n):
        for i in range(0,n):
            #print(k,i)
            #print("aaaa",M[k][i])
            M[k][i] = Truncamento(M[k][i], 5, 3)
    bt = len(b)
    for j in range(0,bt):
        b[j] = Truncamento(b[j],t,t)
        
    print("Matriz Exemplo")
    print(M)
    
    print(" ")
    
    print("Vetor b")
    print(b)
    print("  ")
    
    return M,b
    
    
maquina(M,b,t)

def eliminacao(M,b,t):
    n = len(M)
    m = n*[0]
    for k in range(0,n-1):
        for i in range(k+1,n):
            if eval(M[k][k]) == 0:
                print("ERRO: PIVÔ IGUAL A ZERO")
            m=(eval(M[i][k])/eval(M[k][k]))
            #print("Esse e o m",m)
            M[i][k] = 0
            for j in range(k+1,n):
                #print("M[i][j]",M[i][j])
                #print("M[k][j]",M[k][j])
                
                M[i][j] = eval(M[i][j]) - m*eval(M[k][j])
                
                #print(M[i][j])
                M[i][j] = float(M[i][j])
                
                #M[i][j] = np.around(float(M[i][j]),3)
                M[i][j] = Truncamento(M[i][j],t,t)
                b[i] = str(eval(b[i]) - m*eval(b[k]))
    #print("B",b)
    return M
semPiv = eliminacao(np.copy(M),np.copy(b),t)
print("Matriz final sem pivotamento parcial")
print(semPiv)


def pivoteamentoParcial(A, k, i):
  n = np.shape(A)[0] - 1 #último index
  #print('n Ultimo ', n, '\n')
  
  for k in range(0,2):
        for i in range(0,2):
            #print(A[k][i])
            A[k][i] = eval(A[k][i])
            #print(A[k][i])
    
  #slicing
  np.array( A[ i : n + 1, k ])

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = float(A[ i : n + 1, k ])
  #print("col",col)

  colAbs = np.abs( col )
  #print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  #print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  #print("Troca" ,iChange )

  aux = np.copy( A[ k, : ] )
  #print("aux", aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  #print(A)
  for k in range(0,2):
    for i in range(0,2):
        A[k][i] = Truncamento(A[k][i],t,t)

  return A


def eliminacaoDegauss( A, b, n,t ): #Linha do pivô
    
    for k in np.arange( 0, n ): #
        #print('k ', k)
        for i in np.arange( k + 1, n + 1 ): #Eliminação em cada linha
            #print('i', i )
            A = pivoteamentoParcial(A,k,i) 
            m = (eval(M[i][k])/eval(M[k][k])) #Se for considerada divisão de inteiros dará zero
            #print('m ', m) 
            A[ i, k ] = 0
    #print("BBBBBB",b)
    return A


n = np.shape(A)[0] - 1#último index

t = 3

M = eliminacaoDegauss( np.copy( M ), np.copy( b ), n,t )
print("           ")
print("Matriz final com pivotamento parcial")
print(M)



Matriz Exemplo
[['0.2  *10**-3' '0.2*10**1']
 ['0.2*10**1' '0.2*10**1']]
 
Vetor b
['0.5*10**1', '0.6*10**1']
  
-
Matriz final sem pivotamento parcial
[['0.2  *10**-3' '0.2*10**1']
 ['0' '-0.199*10**3']]
           
Matriz final com pivotamento parcial
[['0.2*10**-3' '0.2*10**1']
 ['0' '0.2*10**1']]


## Resolução dos sistemas triangulares gerados

In [945]:
#Solução
def resolSisTriang(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = eval(b[n-1])/eval(a[n-1][n-1])
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k+1,n):
            s = s + eval(a[k][j])*x[j]
        #print("s",s)   
        #print("x[k]",x[k])
        #print("b[k]",b[k])
        #print("a[k][k]",a[k][k])
        x[k] = (eval(b[k]) - s)/eval(a[k][k])     
        #print("X[k]",x[k])
    return x



resultadoEncontradoComPiv = resolSisTriang(M,b)
resultadoEncontradoSemPiv = resolSisTriang(semPiv,b)
print("Resultado com pivotamento parcial", resultadoEncontradoComPiv)
print("              ")
print("Resultado sem pivotamento parcial", resultadoEncontradoSemPiv)

Resultado com pivotamento parcial [-5000.0, 3.0]
              
Resultado sem pivotamento parcial [25301.50753768844, -0.03015075376884422]


## Resposta exata

In [796]:
matrix = [[0.0002,2],[2,2]] 
vector = [5,6]

resultadoReal = np.linalg.solve(matrix,vector)
print(resultadoReal)

[0.50005001 2.49994999]
