In [ ]:
P/ casa(1)

In [ ]:
https://en.wikipedia.org/wiki/Gaussian_elimination (Fazer o exemplo e dizer por que não funciona)

In [ ]:
P/ casa(2)

In [ ]:
#Duas condições
#Se elemento zero abaixo do pivô: continue. 
#Se um dos pivôs for zero mostrar mensagem de erro
(Sistema não tem solução se o determinante for igual a zero)

In [2]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[k][k] == 0:
                print("Pivo igual a zero, meu")
            m=a[i][k]/a[k][k]
            a[i][k] = 0
            for j in range(k+1,n):
                a[i][j] = a[i][j] - m*a[k][j]
                b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 1 -1  2]
 [ 2  1 -1]
 [-2 -5  3]]
[[ 2]
 [-7]
 [-5]]


In [ ]:
P/ casa(3)

In [ ]:
#Se determinante = 0: mensagem de erro
# else: aplicar gaussElmination
#np.linalg.det(a) pra calcular o determinante

In [17]:
def PivParcial():
    

M = np.array([[1,2,3,4], [0,5,6,7], [0,0,8,9],[0,0,0,10]])
b = np.array([5,4,4,2])

print("Matriz exemplo")
print(M)

def ResolSisTriang(a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k+1,n):
            s = s + a[k][j]*x[j]
        x[k] = (b[k]-s)/a[k][k]
    return x

ResolSisTriang(M,b)
#troc linha por coluna = pivoteamento completo
#troc linha por linha = parcial

Matriz exemplo
[[ 1  2  3  4]
 [ 0  5  6  7]
 [ 0  0  8  9]
 [ 0  0  0 10]]


[2.9950000000000001,
 0.18999999999999995,
 0.27500000000000002,
 0.20000000000000001]

In [ ]:
#Mais uma atividade pra casa, colocar esse código dentro do de resolução de sistema triangular
#Pivoteamento parcial

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


A = Amat
print(A)

k = 1
i = 2
n = np.shape(A)[0] - 1#último index
print('n ', n, '\n')

#slicing
#Pegando a parte que ta abaixo do pivô
print( np.array( A[ i : n + 1, k ] ) )

#Localizando o  maior valor na coluna do pivô, depois do pivô
col = A[ i : n + 1, k ]

colAbs = np.abs( col )
print( 'colAbs \n', colAbs )

#Retorna o index do valor máximo
indexMax = np.argmax( colAbs )
print( indexMax )


#Trocando a coluna
iChange = indexMax + i
print( iChange )

aux = np.copy( A[ k, : ] )
print( aux )

#trocando a linha
A[ k, : ] = np.copy( A[ iChange, : ] )
A[ iChange, : ] = np.copy( aux )

print(A)

In [19]:
M = np.array([[0.0002, 2],[2,2]])
b = np.array([5, 6])
x = np.linalg.solve(M,b)
print(x)

[ 0.50005001  2.49994999]


In [ ]:
#Atividade pra casa
Passar matriz A, matriz B e número de dígitos da máquina. 