In [ ]:
troca a linha 1 com a 3
Então ele multiplica pela Matrix identidade

primeiro resolve o lu e identidade

segundo def retorna lu, p, identidada

In [24]:
import numpy as np

def pivoteamentoParcial(A, k, i):

  n = np.shape(A)[0] - 1 #último index

  #slicing

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )

  indexMax = np.argmax( colAbs )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )


  return A


U = np.array([[3.,(-4.),(1.)], [1.,2.,(2.)], [(4.),(0),(-3.)]])
#b = np.array([1.,2.,3.])
#L = np.zeros([3,3])

print("matriz exemplo")
print(U)
L = np.identity(len(U))
P = np.identity(3)

def FatoracaoLU(U,I):
    n = len(U)
    m = n*[0]
    
    for k in range(0,n):
        
        for i in range(k+1,n):
            print("k,i",k,i)
            U = pivoteamentoParcial(U,k,i)
            I = pivoteamentoParcial(I,k,i)
            m=U[i][k]/U[k][k]
            U[i][k] = 0
            L[i][k] = m
    
            for j in range(k+1,n):
                U[i][j] = U[i][j] - m*U[k][j]
    print(" ")
    print(I)
    print(" ")
    return L, U
                


FatoracaoLU(U,P)

print("Matriz L")
print(L)
print("        ")
print("Matriz U")
print(U)
print("        ")
#print("Multiplicacao de L por U")
#LU = np.dot(L,U)
#print(LU)



matriz exemplo
[[ 3. -4.  1.]
 [ 1.  2.  2.]
 [ 4.  0. -3.]]
k,i 0 1
k,i 0 2
k,i 1 2
 
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]
 
Matriz L
[[ 1.          0.          0.        ]
 [ 0.25        1.          0.        ]
 [ 1.33333333  0.375       1.        ]]
        
Matriz U
[[ 3.         -4.          1.        ]
 [ 0.          5.33333333 -4.33333333]
 [ 0.          0.          4.375     ]]
        


In [ ]:
'''
nL = len(L)
y = nL*[0]

nU = len(U)
x = nU*[0]

def solucaoLy(L,b, n):
    y[0] = b[0]/L[0][0]
    for k in range(1,n-1):
        s = 0
        for j in range(k-1,n):
            s = s + L[k][j]*y[j]
        y[k] = (b[k]-s)/L[k][k]   
        
    return y
  
solucaoLy(L,b,nL)

print(" ")
print("Y = ",y)

def solucaoUx(U,y,n):
    x[n-1] = y[n-1]/U[n-1][n-1]
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k+1,n):
            s = s + U[k][j]*x[j]
        x[k] = (y[k]-s)/U[k][k]                 
    return x  
  
  
solucaoUx(U,y, nU)

print(" ")
print("X = ",x)
'''