In [ ]:

def truncation(num, exp, lim):

  if (int(num.split('.')[0])>0):

    integerSize=str(len(num.split('.')[0]))
    fractional=num.split('.')[0] + num.split('.')[1] 
    if (len(fractional)>lim): fractional=fractional[:lim] 
    
    if(int(integerSize)>exp): fractional='0.' + fractional + '*10^' + str(exp)
    else: fractional='0.' + fractional + '*10^' + integerSize

  else:

    fractional=num.split('.')[1] 

    i=0
    while (True):
      if (fractional[i]=='0'): i+=1
      else: break
    fractional=fractional.replace('0', '', i)

    if (len(fractional)>lim): fractional=fractional[:lim]

    if (i>=exp): fractional='0.' + fractional + '*10^-' + str(exp)
    elif (i==0): fractional='0.' + fractional + '*10^0'
    else: fractional='0.' + fractional + '*10^-' + str(i)

  print('Truncamento:', fractional)

## Google: Gauss Elimination Wiki

In [ ]:
Tem divisão por zero
O código original só considerava valores inteiros, então em um momento houve divisão por zero

In [480]:
#https://en.wikipedia.org/wiki/Gaussian_elimination (Fazer o exemplo e dizer por que não funciona)
M = np.array([[2.,1.,-1.],[-3.,-1.,2.],[-2.,1.,2.]])
b = np.array([[8.],[-11.],[-3.]])

#Matriz = [[1,3,1],[1,1,-1],[3,11,5]] 
#Vetor = [9,1,35]

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
        return print("o DETERMINANTE E ZERO")
    else:
        for k in range(0,n-1):
            for i in range(k+1,n):
                if a[k][k] == 0:
                    print("ERRO: PIVÔ IGUAL A ZERO")
                m=a[i][k]/a[k][k]
                if a[i][k] == 0:
                    continue
                a[i][k] = 0
                for j in range(k+1,n):
                    a[i][j] = a[i][j] - m*a[k][j]
                    b[i] = b[i] - m*b[k]
    print (a)
 
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
[[ 2.   1.  -1. ]
 [ 0.   0.5  0.5]
 [ 0.   0.  -1. ]]
[[  8.]
 [ 13.]
 [-39.]]


## Adicionando condições ao código

In [ ]:
'''
Duas condições:
-Se elemento zero abaixo do pivô: continue. 
-Se um dos pivôs for zero mostrar mensagem de erro
(Sistema não tem solução se o determinante for igual a zero)
'''

In [2]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[k][k] == 0:
                print("ERRO: PIVÔ IGUAL A ZERO")
            m=a[i][k]/a[k][k]
            if a[i][k] == 0:
                continue
            a[i][k] = 0
            for j in range(k+1,n):
                a[i][j] = a[i][j] - m*a[k][j]
                b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

matriz exemplo
[[ 1 -1  2]
 [ 2  1 -1]
 [-2 -5  3]]
[[ 2]
 [-7]
 [-5]]


In [ ]:
'''
Se determinante = 0: mensagem de erro
else: aplicar gaussElmination
np.linalg.det(a) pra calcular o determinante
'''

In [ ]:
import numpy as np
M = np.array([[1,-1,2],[2,1,-1],[-2,-5,3]])
b = np.array([[2],[1],[3]])

print("matriz exemplo")
print(M)

def eliminacao(a,b):
    n = len(a)
    m = n*[0]
    if(np.linalg.det(a)==0):
        return print("o DETERMINANTE E ZERO")
    else:
        for k in range(0,n-1):
            for i in range(k+1,n):
                if a[k][k] == 0:
                    print("ERRO: PIVÔ IGUAL A ZERO")
                m=a[i][k]/a[k][k]
                if a[i][k] == 0:
                    continue
                a[i][k] = 0
                for j in range(k+1,n):
                    a[i][j] = a[i][j] - m*a[k][j]
                    b[i] = b[i] - m*b[k]
    return a
                


eliminacao(M,b)
print(b)

## Inserir o trecho de código abaixo na função de resolução de sistema triangular

In [27]:
#colocar esse código dentro do de resolução de sistema triangular
#Pivoteamento parcial

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


A = Amat
print(A)

k = 1
i = 2
n = np.shape(A)[0] - 1#último index
print('n ', n, '\n')

#slicing
#Pegando a parte que ta abaixo do pivô
print( np.array( A[ i : n + 1, k ] ) )

#Localizando o  maior valor na coluna do pivô, depois do pivô
col = A[ i : n + 1, k ]

colAbs = np.abs( col )
print( 'colAbs \n', colAbs )

#Retorna o index do valor máximo
indexMax = np.argmax( colAbs )
print( indexMax )


#Trocando a coluna
iChange = indexMax + i
print( iChange )

aux = np.copy( A[ k, : ] )
print( aux )

#trocando a linha
A[ k, : ] = np.copy( A[ iChange, : ] )
A[ iChange, : ] = np.copy( aux )

print(A)

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 

[[-3]
 [ 2]]
colAbs 
 [[3]
 [2]]
0
2
[[0 1 0 3]]
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]


In [479]:
import numpy as np

def pivoteamentoParcial(A, k, i):

  n = np.shape(A)[0] - 1 #último index
  print('n Ultimo ', n, '\n')

  #slicing
  print( np.array( A[ i : n + 1, k ] ) )

  #Localizando o  maior valor na coluna do pivô, depois do pivô
  col = A[ i : n + 1, k ]

  colAbs = np.abs( col )
  print( 'colAbs \n', colAbs )

  indexMax = np.argmax( colAbs )
  print( indexMax )


  #Trocando a coluna
  iChange = indexMax + i
  #print( ,iChange )

  aux = np.copy( A[ k, : ] )
  #print( aux )

  A[ k, : ] = np.copy( A[ iChange, : ] )
  A[ iChange, : ] = np.copy( aux )

  print(A)

  return A



def eliminacaoDegauss( A, b, n ): #Linha do pivô
    for k in np.arange( 1, n ): #
        print('k ', k)
        for i in np.arange( k + 1, n + 1 ): #Eliminação em cada linha
            print('i', i )
            A = pivoteamentoParcial(A,k,i) 
            m = A[ i, k ] / A[ k, k ] #Se for considerada divisão de inteiros dará zero
            print('m ', m) 
            A[ i, k ] = 0
            for j in np.arange( k + 1, n + 1 ):
                print('j', j )
        
    return A



b = np.array( [ 5., 6., 7., 15. ] )

Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])

A = Amat
print(A)

n = np.shape(A)[0] - 1#último index
print('n ', n)

eliminacaoDegauss( np.copy( A ), np.copy( b ), n )

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3
k  1
i 2
n Ultimo  3 

[-3  2]
colAbs 
 [3 2]
0
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]
m  -0.3333333333333333
j 2
j 3
i 3
n Ultimo  3 

[2]
colAbs 
 [2]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0  0  3]
 [ 0 -3 -5  7]]
m  -1.5
j 2
j 3
k  2
i 3
n Ultimo  3 

[-5]
colAbs 
 [5]
0
[[ 3  2  4 -1]
 [ 0  2  4  0]
 [ 0  0 -5  7]
 [ 0  0  0  3]]
m  -0.0
j 3


array([[ 3,  2,  4, -1],
       [ 0,  2,  4,  0],
       [ 0,  0, -5,  7],
       [ 0,  0,  0,  3]])

## Resolução de exemplo em sala

In [19]:
M = np.array([[0.0002, 2],[2,2]])
b = np.array([5, 6])
x = np.linalg.solve(M,b)
print(x)

[ 0.50005001  2.49994999]


In [ ]:
#Atividade pra casa
Passar matriz A, matriz B e número de dígitos da máquina. 

Fazer o def que simule a última parte da apresentação Resolução de Sistemas Lineares - Método da Eliminação de Gauss,
na qual um máquina com precisão t é usada obter a resposta de um sistema linear com e sem pivoteamento parcial. 
O def tem como parâmetros a matriz A, b e t dígitos, pelo menos. 
Deve retornar a resposta do sistema e também se a resposta está correta. 
Fazer um código    genérico, que funcione para outras matrizes A e diferentes precisões t. 
Usar o exemplo que foi apresentado em sala de aula para testar o def.

Nota: para somar ou subtrair dois números, o expoente menor deve ser igualado ao expoente maior.

In [478]:
def truncation(num, exp, lim):
  sinal = ''
  if (int(num.split('.')[0])>0 or (int(num.split('.')[0])<0) ) :

    integerSize=str(len(num.split('.')[0]))
    
    
    if(num[0] == '-'):
      sinal = num[0]
      print(sinal)
      num = num.replace(num[0],"")
      fractional = num.split('.')[0]

    elif(num[0]==0 and num[0] != '-'):
        print("pao")
        fractional=num.split('.')[0] + num.split('.')[1] 
    else:
        fractional=num.split('.')[0] 
        

    if(len(fractional)>lim): fractional=fractional[:lim] 
    
    if(int(integerSize)>exp):

      frac = float(sinal + '0.'+fractional)
      new_exp = int(exp) 
      fractional='0.' + fractional + '*10^' + str(exp)
    else: 
      frac = float(sinal +'0.'+fractional)
      new_exp = int(integerSize) 
      fractional='0.' + fractional + '*10^' + integerSize

  else:

    fractional=num.split('.')[1] 

    i=0
    while (True):
      if (fractional[i]=='0'): i+=1
      else: break
    fractional=fractional.replace('0', '', i)

    if (len(fractional)>lim): fractional=fractional[:lim]

    if (i>=exp): 
      frac = float(sinal + '0.'+fractional)
      new_exp = int('-'+ str(exp)) 
      fractional='0.' + fractional + '*10^-' + str(exp)
    elif (i==0): 
      frac = float(sinal + '0.'+fractional)
      new_exp = 0 
      
      fractional='0.' + fractional + '*10^0'
    else: 
      frac = float(sinal + '0.'+fractional)
      str(i)
      new_exp = int('-'+str(i)) 
      fractional='0.' + fractional + '*10^-' + str(i)

  #print('Truncamento:', fractional)
  return fractional

truncation('0.002', 3, 3)



#eliminacao(M,b)

M = np.array([['0.0002     ', '2'] , ['2' , '2']])
b = (['5','6'])


def maquina(M,b):
    #print("Matriz exemplo")
    #print(M)
    
    fracoes = []
    expoentes = []
    
    
    n = len(M)
    for k in range(0,n):
        for i in range(0,n):
            #print(k,i)
            #print("aaaa",M[k][i])
            M[k][i] = truncation(M[k][i], 3, 3)
            
            #Divisão do array pra separar os expoentes
            sliced = M[k][i].split("^")
            
            #Uma nova divisão na primeira parte para separar as fracoes
            sliced[0] = sliced[0].split("*")
            
            #Criacao dos vetores de fracoes e expoentes
            fracoes.append(sliced[0][0])
            expoentes.append(sliced[1])
            #print("Fracao",sliced[0][0])
            #print("Expoente",sliced[1])
            
    bt = len(b)
    for j in range(0,bt):
        b[j] = truncation(b[j],3,3)
        
    print("Matriz")
    print(M)
    
    print(" ")
    
    print("Vetor b")
    print(b)
    print("  ")
    print("Fracoes",fracoes)
    print("Expoentes",expoentes)
    
    
    #AGORA FALTA TRABALHAR COM ESSES NÚMEROS
    
    
    return 
    
    
maquina(M,b)


Matriz
[['0.2  *10^-3' '0.2*10^1']
 ['0.2*10^1' '0.2*10^1']]
 
Vetor b
['0.5*10^1', '0.6*10^1']
  
Fracoes ['0.2  ', '0.2', '0.2', '0.2']
Expoentes ['-3', '1', '1', '1']
